/** Orden sugerido de estudio, usado por la ruta de aprendizaje y la navegación. */
export const RUTA: { semana: number; titulo: string; nota: string; slugs: string[] }[] = [
  {
    semana: 1,
    titulo: "Los tres que vas a usar siempre",
    nota: "Empezá por los patrones más frecuentes y más fáciles de reconocer en código ajeno.",
    slugs: ["strategy", "factory-method", "observer"],
  },
  {
    semana: 2,
    titulo: "Envolver, traducir y simplificar",
    nota: "Los estructurales cotidianos, y Singleton con su crítica incluida.",
    slugs: ["decorator", "adapter", "facade", "singleton"],
  },
  {
    semana: 3,
    titulo: "Estructuras y acciones",
    nota: "Aparecen en toda biblioteca que uses, empezando por la estándar.",
    slugs: ["composite", "iterator", "template-method", "command"],
  },
  {
    semana: 4,
    titulo: "Creación completa y estados",
    nota: "Cerrás los creacionales y ves el primer patrón con transiciones.",
    slugs: ["builder", "prototype", "abstract-factory", "state"],
  },
  {
    semana: 5,
    titulo: "Cadenas, intermediarios y sustitutos",
    nota: "La base de los middlewares, del deshacer y de las cachés.",
    slugs: ["chain-of-responsibility", "mediator", "memento", "proxy"],
  },
  {
    semana: 6,
    titulo: "Los tres difíciles",
    nota: "Bridge, Flyweight y Visitor, ya con contexto suficiente para que tengan sentido.",
    slugs: ["bridge", "flyweight", "visitor"],
  },
  {
    semana: 7,
    titulo: "Núcleo de aplicaciones con LLM",
    nota: "Todo lo que necesitás para que una app con modelos sea mantenible y segura.",
    slugs: [
      "plantilla-de-prompt",
      "adaptador-de-proveedor",
      "cadena-de-prompts",
      "enrutador-de-modelos",
      "herramientas-del-agente",
      "rag",
      "guardarrailes",
      "salida-estructurada",
    ],
  },
  {
    semana: 8,
    titulo: "Agentes, resiliencia, ML y visión",
    nota: "Los patrones que suponen todo lo anterior.",
    slugs: [
      "agente-react",
      "memoria-de-conversacion",
      "cache-semantica",
      "cascada-de-respaldo",
      "orquestador-trabajadores",
      "evaluador-optimizador",
      "tuberia-de-datos",
      "registro-de-modelos",
      "callbacks-de-entrenamiento",
      "checkpoint-y-reanudacion",
      "ensamble-de-modelos",
      "validacion-de-datos",
      "tuberia-de-transformaciones",
      "fuente-de-frames",
      "inferencia-por-lotes",
      "postproceso-de-detecciones",
      "seguimiento-multiobjeto",
    ],
  },
];
